steps:
  - name: 'docker'
    args: [
        'build',
        '-t', 'gcr.io/${PROJECT_ID}/template',
        '--build-arg', 'ENV=${PROJECT_ID}',
        '.' ]
  - name: 'docker'
    args: [
        'push', 'gcr.io/${PROJECT_ID}/template' ]
